<?php
declare(strict_types=1);
$root=dirname(__DIR__);$targets=(string)file_get_contents($root.'/public/api/targets.php');$github=(string)file_get_contents($root.'/src/GitHubClient.php');$builds=(string)file_get_contents($root.'/public/api/builds.php');$worker=(string)file_get_contents($root.'/bin/analysis-worker.php');$migration=(string)file_get_contents($root.'/database/migrations/20260918_011_analysis_queue_and_build_plans.sql').file_get_contents($root.'/database/migrations/20260918_013_materialized_plans.sql').file_get_contents($root.'/database/migrations/20260919_014_analysis_progress.sql');
foreach(['queued','processing','completed','failed','FOR UPDATE SKIP LOCKED','result_encrypted','progress_encrypted','ai_request','ai_result'] as $needle)if(!str_contains($worker.$migration,$needle)){fwrite(STDERR,"Analysis queue lifecycle is missing {$needle}.\n");exit(1);}
foreach(['ready','approved','superseded','dispatched','approved_by','approved_at','plan_sha256'] as $needle)if(!str_contains($builds.$worker.$migration,$needle)){fwrite(STDERR,"Build-plan lifecycle is missing {$needle}.\n");exit(1);}
if(str_contains($targets,'TargetAnalyzer::discover')||str_contains($targets,'AITargetAnalyzer')){fwrite(STDERR,"Target HTTP requests must not execute source or AI analysis.\n");exit(1);}
if(!str_contains($builds,"status='completed'")||!str_contains($builds,'result_encrypted')){fwrite(STDERR,"Dispatch must consume completed immutable analysis.\n");exit(1);}
foreach(['workflow_encrypted','workflow_sha256','materialized_at','BuildMaterializer::materialize','readyTargets','targetFailures','No discovered hardware target could be safely materialized'] as $needle)if(!str_contains($worker.$migration,$needle)){fwrite(STDERR,"Worker materialization is missing {$needle}.\n");exit(1);}
if(str_contains($builds,'WorkflowEngine::workflow(')||str_contains($builds,'sourceBundle(')){fwrite(STDERR,"Dispatch request still materializes source or workflows.\n");exit(1);}
foreach(['sourceRevision','knownSourceCommit','/compare/','ci: configure ESPForge for ',".github/workflows/espforge-build.yml",'with_build_verification','build_verification'] as $needle)if(!str_contains($github.$targets,$needle)){fwrite(STDERR,"Persistent target verification is missing {$needle}.\n");exit(1);}
if(substr_count($worker,'->discoverLibraries(')!==1||substr_count($worker,'->sourceBundle(')!==1){fwrite(STDERR,"Worker must analyze repository source and AI libraries once per job, not once per target.\n");exit(1);}
echo "Analysis queue and build-plan policy tests passed.\n";
