CREATE TABLE users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL,
 password_hash VARCHAR(255) NULL, session_version INT UNSIGNED NOT NULL DEFAULT 1, github_id VARCHAR(64) NULL UNIQUE, google_id VARCHAR(128) NULL UNIQUE,
 github_token TEXT NULL, ai_provider VARCHAR(32) NULL, ai_api_key TEXT NULL, ai_key_fingerprint CHAR(64) NULL UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE password_reset_tokens (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL,
 token_hash CHAR(64) NOT NULL UNIQUE, expires_at TIMESTAMP NOT NULL, used_at TIMESTAMP NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX(user_id, created_at), INDEX(expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE repositories (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, repo_url VARCHAR(500) NOT NULL,
 full_name VARCHAR(255) NOT NULL, default_branch VARCHAR(100) DEFAULT 'main', framework VARCHAR(40) NULL,
 workflow_config MEDIUMTEXT NULL, status VARCHAR(30) DEFAULT 'connected', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id), UNIQUE KEY uq_repositories_user_full_name(user_id, full_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE builds (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, repo_id BIGINT UNSIGNED NOT NULL, build_uuid CHAR(36) NULL UNIQUE, github_run_id BIGINT UNSIGNED NULL,
 status VARCHAR(30) DEFAULT 'queued', conclusion VARCHAR(30) NULL, logs MEDIUMTEXT NULL, artifact_url VARCHAR(1000) NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, completed_at TIMESTAMP NULL,
 FOREIGN KEY (repo_id) REFERENCES repositories(id) ON DELETE CASCADE, INDEX(repo_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE audit_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, event_type VARCHAR(80) NOT NULL,
 ip_hash CHAR(64) NULL, metadata_json JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(user_id, created_at), INDEX(event_type, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE flash_configs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, name VARCHAR(100) NOT NULL,
 chip VARCHAR(40) DEFAULT 'esp32', baud INT DEFAULT 460800, flash_mode VARCHAR(20) DEFAULT 'dio', offsets_json JSON NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
