CREATE TABLE analysis_jobs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 repo_id BIGINT UNSIGNED NOT NULL,
 source_commit_sha CHAR(40) NOT NULL,
 analyzer_version VARCHAR(40) NOT NULL,
 status ENUM('queued','processing','completed','failed') NOT NULL DEFAULT 'queued',
 attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
 result_encrypted MEDIUMTEXT NULL,
 error_message VARCHAR(500) NULL,
 available_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 started_at TIMESTAMP NULL,
 completed_at TIMESTAMP NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (repo_id) REFERENCES repositories(id) ON DELETE CASCADE,
 UNIQUE KEY uq_analysis_job_revision(repo_id,source_commit_sha,analyzer_version),
 INDEX idx_analysis_jobs_claim(status,available_at,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE build_plans (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 plan_uuid CHAR(36) NOT NULL UNIQUE,
 repo_id BIGINT UNSIGNED NOT NULL,
 source_commit_sha CHAR(40) NOT NULL,
 analyzer_version VARCHAR(40) NOT NULL,
 target_id VARCHAR(190) NOT NULL,
 target_name VARCHAR(120) NOT NULL,
 target_config_json JSON NOT NULL,
 plan_sha256 CHAR(64) NOT NULL,
 status ENUM('ready','approved','superseded','dispatched','failed') NOT NULL DEFAULT 'ready',
 approved_by BIGINT UNSIGNED NULL,
 approved_at TIMESTAMP NULL,
 dispatched_at TIMESTAMP NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (repo_id) REFERENCES repositories(id) ON DELETE CASCADE,
 FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
 UNIQUE KEY uq_build_plan_revision_target(repo_id,source_commit_sha,analyzer_version,target_id),
 INDEX idx_build_plans_repo_status(repo_id,status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
